export const categories = [
    {
        name: "Artist",
        commands: [
            { name: "artists", description: "Shows list of artists and their leaked discography", usage: ".artists" },
            { name: "carti", description: "Search for song snippets by artist Playboi Carti", usage: ".carti <snippet name>" },
            { name: "cartiinfo", description: "Searches for information about a Playboi Carti song", usage: ".cartiinfo <song name>" },
            { name: "cartilyric", description: "Get prompted lyrics from a Playboi Carti song and your objective is to guess the song", usage: ".cartilyric [game]" },
            { name: "dojainfo", description: "Searches for information about a Doja Cat song", usage: ".dojainfo <song name>" },
            { name: "gunnainfo", description: "Search for information about a Gunna song", usage: ".gunnainfo <song name>" },
            { name: "juiceera", description: "Gives what era a Juice WRLD song is", usage: ".juiceera <song name>" },
            { name: "juicegb", description: "Provides information about a Juice WRLD song groupbuy", usage: ".juicegb <song name>" },
            { name: "juiceinfo", description: "Searches for information about a Juice WRLD song", usage: ".juiceinfo <song name>" },
            { name: "juicelyric", description: "Get prompted lyrics from a Juice WRLD song and your objective is to guess the song", usage: ".juicelyric [game]" },
            { name: "juiceprod", description: "Searches for Juice WRLD songs produced by a given producer", usage: ".juiceprod <producer name>" },
            { name: "juicesession", description: "Searches and lists all Juice WRLD songs recorded on the given date", usage: ".juicesession <date>" },
            { name: "kanye", description: "Searches for information about a Kanye West song", usage: ".kanye <song name>" },
            { name: "keninfo", description: "Searches for information about a Ken Carson song", usage: ".keninfo <song name>" },
            { name: "kingvon", description: "Search for snippets for songs by King Von", usage: ".kingvon <snippet name>" },
            { name: "leak", description: "Searches for a leak by Juice WRLD", usage: ".leak <song name>" },
            { name: "ogfiles", description: "Shows list of og files for Juice WRLD songs", usage: ".ogfiles" },
            { name: "popinfo", description: "Search for information about a Pop Smoke song", usage: ".popinfo <song name>" },
            { name: "ski", description: "Searches for information about a Ski Mask The Slump God song", usage: ".ski <song name>" },
            { name: "snip", description: "Search for snippets for songs by Juice WRLD", usage: ".snip <snippet name>" },
            { name: "thuginfo", description: "Searches for information about a Young Thug song", usage: ".thuginfo <song name>" },
            { name: "trippie", description: "Search for snippets for songs by Trippie Redd", usage: ".trippie <snippet name>" },
            { name: "trippieinfo", description: "Searches for information about a Trippie Redd song", usage: ".trippieinfo <song name>" },
            { name: "uziinfo", description: "Searches for information about a Lil Uzi Vert song", usage: ".uziinfo <song name>" },
            { name: "yeat", description: "Search for snippets for songs by Yeat", usage: ".yeat <snippet name>" },
            { name: "yeatinfo", description: "Searches for information about a Yeat song", usage: ".yeatinfo <song name>" },
        ],
    },
    {
        name: "Fun & Games",
        commands: [
            { name: "8ball", description: "Ask a question to the all knowing 8ball", usage: ".8ball <question>" },
            { name: "bam", description: "Make someone think you're banning them", usage: ".bam <user>" },
            { name: "banroulette", description: "Play a game of ban roulette where the loser gets banned", usage: ".banroulette" },
            { name: "ben", description: "Ask Talking Ben any question you want", usage: ".ben <question>" },
            { name: "blacktea", description: "Play BlackTea with your friends! Subcommands: leaderboard, endgame", usage: ".blacktea (subcommand)" },
            { name: "bubblewrap", description: "Discord ASMR", usage: ".bubblewrap" },
            { name: "coinflip", description: "Flip a coin for heads or tails", usage: ".coinflip" },
            { name: "connect4", description: "Play a game of Connect Four with someone", usage: ".connect4 <user>" },
            { name: "enlarge", description: "Enlarge an emoji to see it bigger", usage: ".enlarge <emoji>" },
            { name: "fakemsg", description: "Create fake messages as another user", usage: ".fakemsg <user> <text>" },
            { name: "fight", description: "Fight another user", usage: ".fight <user>" },
            { name: "gay", description: "Measure your gayness", usage: ".gay (user)" },
            { name: "minesweeper", description: "Play a game of minesweeper", usage: ".minesweeper" },
            { name: "neverhaveiever", description: "Play a game of never have I ever", usage: ".neverhaveiever" },
            { name: "ocr", description: "Convert image to text", usage: ".ocr <attachment>" },
            { name: "oogway", description: "Oogay meme quote", usage: ".oogway <text>" },
            { name: "optionpoll", description: "Create an option poll with a max of 9 options", usage: ".optionpoll <options seperated by comma>" },
            { name: "penis", description: "See how big your shlong is", usage: ".penis" },
            { name: "poll", description: "Create a poll for users to choose from", usage: ".poll <message>" },
            { name: "quickpoll", description: "Reacts to your message with poll emojis allowing users to vote", usage: ".quickpoll" },
            { name: "rockpaperscissors", description: "Play a game of rock paper scissors against another user", usage: ".rockpaperscissors <user>" },
            { name: "snake", description: "Play a game of snake", usage: ".snake" },
            { name: "texttospeech", description: "Text to speech", usage: ".tts <text>" },
            { name: "tictactoe", description: "Play a game of tic-tac-toe against another user", usage: ".tictactoe <user>" },
            { name: "translate", description: "Translate text from another language", usage: ".translate <language> <text>" },
            { name: "wordle", description: "Play a game of wordle", usage: ".wordle" },
        ],
    },
    {
        name: "Information",
        commands: [
            { name: "avatar", description: "See the display avatar for yourself or another user", usage: ".avatar (user)" },
            { name: "banner", description: "See the display banner for yourself or another user", usage: ".banner (user)" },
            { name: "botinfo", description: "See information and statistics about the bot", usage: ".botinfo" },
            { name: "botinvite", description: "Get the bot invite for another bot", usage: ".botinvite <bot>" },
            { name: "bots", description: "View what bots are in the guild", usage: ".bots" },
            { name: "boosts", description: "See the guild's boost level and tier", usage: ".boosts" },
            { name: "color", description: "View the color of a given hexcode or get a random color", usage: ".color (hexcode)" },
            { name: "firstmessage", description: "See the first message sent in the channel", usage: ".firstmessage" },
            { name: "help", description: "Display information about commands and subcommands.", usage: ".help (command)" },
            { name: "id", description: "Get a user's discord ID", usage: ".id <user>" },
            { name: "invite", description: "Get Moonlight's bot invite to add it to another guild", usage: ".invite" },
            { name: "joined", description: "See your own or another user's joined date in the guild", usage: ".joined (user)" },
            { name: "membercount", description: "View the guild's member count", usage: ".membercount" },
            { name: "premium", description: "See information about what Moonlight premium offers", usage: ".premium" },
            { name: "roleinfo", description: "View information about a given role in the guild", usage: ".roleinfo <role>" },
            { name: "rolelist", description: "View all the roles in the guild", usage: ".rolelist" },
            { name: "rolemembers", description: "View all the users who have a given role in the guild", usage: ".rolemembers <role>" },
            { name: "serverbanner", description: "View the guild server banner", usage: ".serverbanner" },
            { name: "serveremojis", description: "View all the emojis in the guild", usage: ".serveremojis" },
            { name: "servericon", description: "View the guild's icon", usage: ".servericon" },
            { name: "serverinfo", description: "View information about the guild", usage: ".serverinfo" },
            { name: "serverinvite", description: "Generate a invite for the guild", usage: ".serverinvite" },
            { name: "test", description: "Tests if bot is working and online", usage: ".test" },
            { name: "timer", description: "Schedule a timer to remind you about a task", usage: ".timer <time>" },
            { name: "uptime", description: "See how long the bot has been up for", usage: ".uptime" },
            { name: "userinfo", description: "View information about yourself or another user", usage: ".userinfo (user)" },
            { name: "userroles", description: "View what roles you or another user in the guild has", usage: ".userroles (user)" },
        ],
    },
    {
        name: "Lastfm",
        commands: [
            { name: "lastfm", description: "View information and statistics about your lastfm account", usage: ".lastfm (subcommand)" },
            { name: "lastfm cc", description: "Create a lastfm custom command which will show your current.last played track when you say the word", usage: ".lastfm cc <trigger>" },
            { name: "lastfm collage", description: "Create a lastfm album collage using the default 3x3 grid and overall timeframe or a custom grid (10x10 max) and timeframe", usage: ".lastfm collage (grid size) (timeframe)" },
            { name: "lastfm color", description: "Set a color you'd like your lastfm commands embeds to have", usage: ".lastfm color" },
            { name: "lastfm gwk", description: "View who knows a given.current playing artist in all bot guilds", usage: ".lastfm gwk (artist)" },
            { name: "lastfm gwka", description: "View who knows a given.current playing album in all bot guilds", usage: ".lastfm gwka (artist - album)" },
            { name: "lastfm gwkt", description: "View who knows a given.current playing track in all bot guilds", usage: ".lastfm gwkt (artist - track)" },
            { name: "lastfm help", description: "View the lastfm help menu with all the commands you can use", usage: ".lastfm help" },
            { name: "lastfm plays", description: "See how many plays you have for a given.current playing track", usage: ".lastfm plays (artist - track)" },
            { name: "lastfm playsalbum", description: "See how many plays you have for a given.current playing album", usage: ".lastfm playsalbum (artist - album)" },
            { name: "lastfm playsartist", description: "See how many plays you have for a given.current playing artist", usage: ".lastfm playsartist (artist)" },
            { name: "lastfm profile", description: "View your lastfm profile and stats", usage: ".lastfm profile" },
            { name: "lastfm reactiondown", description: "Set a custom downvote reaction for your lastfm nowplaying embed", usage: ".lastfm reactiondown <emoji>" },
            { name: "lastfm reactions", description: "Set custom upvote and downvote reactions for your lastfm nowplaying embed", usage: ".lastfm reactions <emojis seperated by space>" },
            { name: "lastfm reactionup", description: "Set a custom upvote reaction for your lastfm nowplaying embed", usage: ".lastfm reactionup <emoji>" },
            { name: "lastfm recent", description: "View your last 10 played recent tracks", usage: ".lastfm recent" },
            { name: "lastfm scrobbles", description: "See how many lastfm scrobbles you have", usage: ".lastfm scrobbles" },
            { name: "lastfm set", description: "Connect your lastfm account with Moonlight by providing your lastfm username", usage: ".lastfm set <last.fm username>" },
            { name: "lastfm style", description: "Pick between 9 different lastfm nowplaying embed styles that you'd like to see when you use the command", usage: ".lastfm style <style number choice>" },
            { name: "lastfm stylereset", description: "Reverts back to the default lastfm nowplaying embed", usage: ".lastfm stylereset" },
            { name: "lastfm tab", description: "View your top 10 played albums, default is set to overall", usage: ".lastfm tab (timeframe)" },
            { name: "lastfm tar", description: "View your top 10 played artists, default is set to overall", usage: ".lastfm tar (timeframe)" },
            { name: "lastfm taste", description: "Compare your lastfm artists with another user to see if you have a similar taste in artists", usage: ".lastfm taste <user>" },
            { name: "lastfm tt", description: "View your top 10 tracks for a given artist or the one you're currently listening to", usage: ".lastfm tt (artist)" },
            { name: "lastfm ttt", description: "View your top 10 played tracks, default is set to overall", usage: ".lastfm ttt (timeframe)" },
            { name: "lastfm unlink", description: "Unlink your lastfm account with Moonlight", usage: ".lastfm unlink" },
            { name: "lastfm url", description: "Set a custom album artwork for the current.last playing song album", usage: ".lastfm url <image url>" },
            { name: "lastfm wk", description: "View who in the server knows a given.current playing artist", usage: ".lastfm wk (artist)" },
            { name: "lastfm wka", description: "View who in the server knows a given.current playing album", usage: ".lastfm wka (artist - album)" },
            { name: "lastfm wkt", description: "View who in the server knows a given.current playing track", usage: ".lastfm wkt (artist - track)" },
            { name: "lfset", description: "Connect your lastfm account with Moonlight by providing your lastfm username", usage: ".lfset <username>" },
            { name: "nowplaying", description: "View yours or another user's current.last played track on lastfm", usage: ".nowplaying (user)" },
            { name: "statsfm", description: "View information and statistics about your Spotify account", usage: ".statsfm (subcommand)" },
            { name: "statsfm recent", description: "View your recently played tracks", usage: ".statsfm recent" },
            { name: "statsfm set", description: "Connect your Stats.FM account with Moonlight by providing your Stats.FM username", usage: ".statsfm set <stats.fm username>" },
            { name: "statsfm tar", description: "View your top played artists, default is set to lifetime", usage: ".statsfm tar (timeframe)" },
            { name: "statsfm tt", description: "View your top played tracks, default is set to lifetime", usage: ".statsfm tt (timeframe)" },
        ],
    },
    {
        name: "Moderation",
        commands: [
            { name: "ban", description: "Ban a user from the guild", usage: ".ban <user>" },
            { name: "botclear", description: "Clear messages by bots in channel", usage: ".botclear" },
            { name: "clearsnipe", description: "Clear sniped messages in the collection array", usage: ".clearsnipe" },
            { name: "dmban", description: "Ban members from guild without alerting them with dm message", usage: ".dmban <user>" },
            { name: "editsnipe", description: "View recently edited messages in the channel", usage: ".editsnipe" },
            { name: "hackban", description: "Ban a user that is not in the guild", usage: ".hackban <user id>" },
            { name: "imagemute", description: "Revoke permission from a user to send images in the channel", usage: ".imagemute <user>" },
            { name: "imageunmute", description: "Restore a user's permission to send images in the channel", usage: ".imageunmute <user>" },
            { name: "jail", description: "Revoke user's ability to interact with the guild, locked to jail channel", usage: ".jail <user>" },
            { name: "kick", description: "Kick a user from the guild", usage: ".kick <user>" },
            { name: "lock", description: "Lock a channel, regular members cannot type without necessary permissions", usage: ".lock (channel)" },
            { name: "lockdown", description: "Configure the guild's lockdown settings in case of raid or other purpose", usage: ".lockdown <subcommand>" },
            { name: "lockdown add", description: "Add a channel to the guild's lockdown settings, channel will be locked when lockdown is on", usage: ".lockdown add <channel>" },
            { name: "lockdown list", description: "View all the channels that will remained locked when lockdown is on", usage: ".lockdown list" },
            { name: "lockdown off", description: "Turn the guild's lockdown feature off", usage: ".lockdown off" },
            { name: "lockdown on", description: "Turn the guild's lockdown feature on", usage: ".lockdown on" },
            { name: "lockdown remove", description: "Remove a channel from the guild's lockdown settings, channel will be unlocked when lockdown is on", usage: ".lockdown remove <channel>" },
            { name: "massunban", description: "Unban all the users in the guild ban list", usage: ".massunban" },
            { name: "mute", description: "Revoke permission from a user to send messages in the channel", usage: ".mute <user>" },
            { name: "purge", description: "Delete a number of messages in the channel", usage: ".purge <amount>" },
            { name: "reactionmute", description: "Revoke permission from a user to react to messages in the channel", usage: ".rmute <user>" },
            { name: "reactionsnipe", description: "View recently reacted messages in the channel, even if users unreact", usage: ".reactionsnipe" },
            { name: "reactionunmute", description: "Restore a user's permission to react to images in the channel", usage: ".runmute <user>" },
            { name: "snipe", description: "View recently deleted messages in the channel", usage: ".snipe" },
            { name: "softban", description: "Bans a user from the guild and then immediately unbans them", usage: ".softban <user>" },
            { name: "unban", description: "Unbans a user from the guild", usage: ".unban <user>" },
            { name: "unjail", description: "Restores user's ability to interact with the guild and see all channels", usage: ".unjail <user>" },
            { name: "unlock", description: "Unlock a channel, allowing users to send messages", usage: ".unlock (channel)" },
            { name: "unmute", description: "Restore user's permission to send messages in the channel", usage: ".unmute <user>" },
            { name: "warn", description: "User warning settings and data", usage: ".warn" },
            { name: "warn clear", description: "Clear all of a user's warnings", usage: ".warn clear <user>" },
            { name: "warn list", description: "View all the warnings a user has been given", usage: ".warn list <user>" },
            { name: "warn remove", description: "Delete a user's warning from its number in the list", usage: ".warn remove <user> <warning number>" },
        ],
    },
    {
        name: "Economy",
        commands: [
            { name: "balance", description: "View yours or another user's wallet balance", usage: ".balance (user)" },
            { name: "beg", description: "If you're broke just beg for money", usage: ".beg" },
            { name: "blackjack", description: "Play a game of blackjack against the dealer to win coins", usage: ".blackjack <amount>" },
            { name: "crash", description: "Play a game of crash and try and win before you lose", usage: ".crash <amount>" },
            { name: "crime", description: "Earn coins by committing a crime", usage: ".crime" },
            { name: "daily", description: "Earn a random number of coins (0-500) daily", usage: ".daily" },
            { name: "deposit", description: "Deposit your coins to your bank to avoid losing it all", usage: ".deposit <amount>" },
            { name: "drop", description: "Drop some coins for another user to collect by saying 'collect'", usage: ".drop <amount>" },
            { name: "economy", description: "Manage a user's economy balance (Admin only)", usage: ".economy <add|remove|set> <user> <amount>" },
            { name: "gamble", description: "Gamble your coins to either lose it or win it back", usage: ".gamble <amount>" },
            { name: "inventory", description: "View your Moonlight song inventory or another user's inventory", usage: ".inventory" },
            { name: "leaderboard", description: "View the global coin leaderboard, showing the top users who have the most coins", usage: ".leaderboard" },
            { name: "leaderboard guild", description: "View the users who have the most coins in the guild", usage: ".leaderboard guild" },
            { name: "pay", description: "Give another user some coins for them to use", usage: ".pay <user> <amount>" },
            { name: "profile", description: "View your economy profile and stats", usage: ".profile (user)" },
            { name: "rob", description: "Attempt to rob a random user in the server. Need 3 participants in order to successfully rob", usage: ".rob" },
            { name: "roulette", description: "Play a game of roulette to earn coins", usage: ".roulette <amount> <color>" },
            { name: "shop", description: "Buy and sell different songs from the Moonlight shop", usage: ".shop" },
            { name: "shop buy", description: "Buy a song from the shop and have it show in your inventory", usage: ".shop buy" },
            { name: "shop sell", description: "Sell a song from the shop in exchange for coins", usage: ".shop sell" },
            { name: "skull", description: "View the skull economy stats", usage: ".skull" },
            { name: "skull debtleaderboard", description: "View the skull economy debt leaderboard with the users who have the lowest skullworth", usage: ".skull debtleaderboard" },
            { name: "skull leaderboard", description: "View the skull economy leaderboard with the users who have the most skulls", usage: ".skull leaderboard" },
            { name: "skull serverleaderboard", description: "View the skull economy leaderboard with the users who have the most skulls in the server", usage: ".skull serverleaderboard" },
            { name: "skulls", description: "View your or another user's skull worth within the skull economy", usage: ".skulls (user)" },
            { name: "slots", description: "Play a game of slots to earn coins", usage: ".slots <amount>" },
            { name: "sob", description: "View the sob economy stats", usage: ".sob" },
            { name: "sob debtleaderboard", description: "View the sob economy debt leaderboard with the users who have the lowest sobworth", usage: ".sob debtleaderboard" },
            { name: "sob leaderboard", description: "View the sob economy leaderboard with the users who have the most sobs", usage: ".sob leaderboard" },
            { name: "sob serverleaderboard", description: "View the sob economy leaderboard with the users who have the most sobs in the server", usage: ".sob serverleaderboard" },
            { name: "sob worthleaderboard", description: "View the sob economy sobworth leaderboard with the users who have the highest sobworth", usage: ".sob worthleaderboard" },
            { name: "sobs", description: "View your or another user's sob worth within the sob economy", usage: ".sobs (user)" },
            { name: "supergamble", description: "12x your coins if you roll and land on a number 90 or more", usage: ".supergamble <amount>" },
            { name: "trade", description: "Initiate a trade with another user", usage: ".trade @user" },
            { name: "withdraw", description: "Withdraw money from your bank to use for economy commands", usage: ".withdraw <amount>" },
            { name: "work", description: "Earn coins (100-1000) by working", usage: ".work" },
        ],
    },
    {
        name: "Roleplay",
        commands: [
            { name: "backshots", description: "Backshots gif", usage: ".backshots <user>" },
            { name: "bark", description: "Random dog barking", usage: ".bark" },
            { name: "catboy", description: "Random catboy gif", usage: ".catboy" },
            { name: "catgirl", description: "Random catgirl gif", usage: ".catgirl" },
            { name: "cuddle", description: "Cuddle with another user", usage: ".cuddle <user>" },
            { name: "feed", description: "Feed another user", usage: ".feed <user>" },
            { name: "fuck", description: "IYKYK", usage: ".fuck <user>" },
            { name: "hug", description: "Give someone a hug", usage: ".hug <user>" },
            { name: "kiss", description: "Give someone a kiss", usage: ".kiss <user>" },
            { name: "meow", description: "Random cat meow gif.image", usage: ".meow" },
            { name: "pat", description: "Give someone a pat on the back", usage: ".pat <user>" },
            { name: "poke", description: "Poke someone", usage: ".poke <user>" },
            { name: "punch", description: "Mad? Punch someone", usage: ".punch <user>" },
            { name: "slap", description: "Mad? Slap someone", usage: ".slap <user>" },
            { name: "spit", description: "Gross but spit on someone", usage: ".spit <user>" },
            { name: "threesome", description: "IYKYK", usage: ".threesome <user> <user>" },
            { name: "wink", description: "Wink at someone", usage: ".wink <user>" },
        ],
    },
    {
        name: "Search",
        commands: [
            { name: "ai", description: "Create an ai image based on your search prompt", usage: ".ai <prompt>" },
            { name: "dbree", description: "Fetches and downloads content from Dbree", usage: ".dbree <link>" },
            { name: "google", description: "Search a query on Google", usage: ".google <query>" },
            { name: "image", description: "Searches for images based on the user query", usage: ".image <query>" },
            { name: "itunes", description: "Search for songs or download from Apple Music", usage: ".itunes <subcommand>" },
            { name: "itunes rip", description: "Download a song from Apple Music", usage: ".itunes rip <link>" },
            { name: "itunes search", description: "Search for a song on Apple Music", usage: ".itunes search <query>" },
            { name: "krakenfiles", description: "Fetches and downloads content from krakenfiles.com", usage: ".krakenfiles <link>" },
            { name: "leakthis", description: "Configure the leakthis settings to have forum posts sent in your server", usage: ".leakthis" },
            { name: "leakthis channel", description: "Set the channel where you want leakthis posts to be sent", usage: ".leakthis channel <channel>" },
            { name: "leakthis data", description: "See the server's leakthis configuration data, if it exists", usage: ".leakthis data" },
            { name: "leakthis filterartist", description: "Configure what artists you want to have forum posts sent for, default is all but. To add multiple artists, seperate names by a comma", usage: ".leakthis filterartist <artists>" },
            { name: "leakthis filtertag", description: "Configure what tags (LEAK, SNIPPET, EARLY, DEMO) you want to have forum posts sent for, default is all but. To add multiple tags, seperate names by a comma", usage: ".leakthis filtertag <tags>" },
            { name: "leakthis reset", description: "Delete all the leakthis configuration data", usage: ".leakthis reset" },
            { name: "lyrics", description: "Find a song or lyrics using Genius Api", usage: ".lyrics <song name or lyrics>" },
            { name: "mp3tag", description: "Can tag files with song name, artist, and album and add custom cover art", usage: ".mp3tag <file>" },
            { name: "mp4", description: "Create an MP4 overlay with a media and mp3 attachment", usage: ".mp4 <image> <mp3>" },
            { name: "rip", description: "Fetches and downloads content from SoundCloud, X, TikTok, and Instagram", usage: ".rip <link>" },
            { name: "soundcloud", description: "Fetches and downloads content from SoundCloud", usage: ".soundcloud <link or query>" },
            { name: "spotify", description: "Fetches Spotify and gives results for a query", usage: ".spotify <query>" },
            { name: "urban", description: "Search for words on Urban Dictionary", usage: ".urban <query>" },
            { name: "youtube", description: "Search for videos on YouTube", usage: ".youtube <query>" },
        ],
    },
    {
        name: "Server Tools",
        commands: [
            { name: "addemojis", description: "Adds a emoji from different servers", usage: ".addemojis <emoji>" },
            { name: "antiadvertising", description: "Configure server anti-advertising for users to post server invites", usage: ".antiadvertising" },
            { name: "antiadvertising off", description: "Turn off the server's anti-advertisting to allow users to post links to other servers", usage: ".antiadvertising off" },
            { name: "antiadvertising on", description: "Turn on the server's anti-advertisting to prevent users from posting links to other servers", usage: ".antiadvertising on" },
            { name: "antialt", description: "Configure server anti-alt for users who have new accounts", usage: ".antialt" },
            { name: "antialt off", description: "Turn off the server's anti-alt to allow all users to join the server regardless of account age", usage: ".antialt off" },
            { name: "antialt on", description: "Turn on the server's anti-alt to prevent users who created accounts younger than 2 weeks to join the server", usage: ".antialt on" },
            { name: "antijoin", description: "Configure server anti-join for users to join the server", usage: ".antijoin" },
            { name: "antijoin off", description: "Turn off the server's anti-join to allow all users to join the server", usage: ".antijoin off" },
            { name: "antijoin on", description: "Turn on the server's anti-join to prevent users from joining the server", usage: ".antijoin on" },
            { name: "antilink", description: "Configure server anti-link for users to post links in the server", usage: ".antilink" },
            { name: "antilink off", description: "Turn off the server's anti-link to allow users to post links in the server", usage: ".antilink off" },
            { name: "antilink on", description: "Turn on the server's anti-link to prevent users from posting links in the server", usage: ".antilink on" },
            { name: "antimp3", description: "Configure server anti-mp3 for users to post audio files", usage: ".antimp3" },
            { name: "antimp3 allow", description: "Allow certain channel ability to send mp3 files", usage: ".antimp3 allow <channel>" },
            { name: "antimp3 disallow", description: "Remove a channel from the allowed channels list", usage: ".antimp3 disallow <channel>" },
            { name: "antimp3 off", description: "Turn off the server's anti-mp3 to allow users to post audio files in the server", usage: ".antimp3 off" },
            { name: "antimp3 on", description: "Turn on the server's anti-mp3 to prevent users from posting audio files in the server", usage: ".antimp3 on" },
            { name: "antinuke", description: "Antinuke to protect your server", usage: ".antinuke (subcommand) <args>" },
            { name: "antinuke admin", description: "Manage Antinuke admins (add.remove)", usage: ".antinuke admin <add|remove> <user>" },
            { name: "antinuke admins", description: "View all Antinuke admins", usage: ".antinuke admins" },
            { name: "antinuke ban", description: "Prevent mass member ban", usage: ".antinuke ban <on|off> --do <punishment>" },
            { name: "antinuke botadd", description: "Prevent new bot additions", usage: ".antinuke botadd <on|off>" },
            { name: "antinuke channel", description: "Prevent mass channel create and delete", usage: ".antinuke channel <on|off> --do <punishment> --threshold <number>" },
            { name: "antinuke config", description: "View server configuration for Antinuke", usage: ".antinuke config" },
            { name: "antinuke emoji", description: "Prevent mass emoji delete", usage: ".antinuke emoji <on|off> --do <punishment> --threshold <number>" },
            { name: "antinuke kick", description: "Prevent mass member kick", usage: ".antinuke kick <on|off> --do <punishment> --threshold <number>" },
            { name: "antinuke role", description: "Prevent mass role delete", usage: ".antinuke role <on|off> --do <punishment> --threshold <number>" },
            { name: "antinuke vanity", description: "Punish users that change the server vanity", usage: ".antinuke vanity <on|off> --do <punishment>" },
            { name: "antinuke webhook", description: "Prevent mass webhook creation", usage: ".antinuke webhook <on|off> --do <punishment> --threshold <number>" },
            { name: "antinuke whitelist", description: "Whitelist a member from triggering Antinuke", usage: ".antinuke whitelist <user or bot ID>" },
            { name: "antispam", description: "Configure server anti-spam to prevent users from spamming the channel with the same message", usage: ".antispam" },
            { name: "antispam off", description: "Turn off the server's anti-spam to allow users to spam messages", usage: ".antispam off" },
            { name: "antispam on", description: "Turn on the server's anti-spam to prevent users from spamming messages", usage: ".antispam on" },
            { name: "autorole", description: "Configure the server's autorole settings for users joining the server", usage: ".autorole" },
            { name: "autorole check", description: "View what the current server autorole role is assigned", usage: ".autorole check" },
            { name: "autorole off", description: "Turn off the server's autorole, users won't be given any role upon joining", usage: ".autorole off" },
            { name: "autorole set", description: "Set the autorole role for users to recieve upon joining the server", usage: ".autorole set <role>" },
            { name: "boosterrole", description: "Users who boost the server are able to create a booster role that they can customize", usage: ".boosterrole" },
            { name: "boosterrole create", description: "Creates a user's booster role with a random color and their name", usage: ".boosterrole create" },
            { name: "boosterrole hexcode", description: "Changes the color of your exisiting booster role", usage: ".boosterrole hexcode <color>" },
            { name: "boosterrole icon", description: "Add a role icon to your booster role", usage: ".boosterrole icon <emoji or link>" },
            { name: "boosterrole info", description: "Shows information about a user's booster role", usage: ".boosterrole info <user>" },
            { name: "boosterrole list", description: "Lists all of the booster roles in the server", usage: ".boosterrole list" },
            { name: "boosterrole remove", description: "Deletes your booster role if you have one", usage: ".boosterrole remove" },
            { name: "boosterrole rename", description: "Renames your booster role if you have one", usage: ".boosterrole rename <new name>" },
            { name: "boosterrole set", description: "Staff: Set the discord made booster role so user booster roles can be made above it", usage: ".boosterrole set <discord booster role>" },
            { name: "counter", description: "Manage server stats counter that displays information about the server", usage: ".counter" },
            { name: "counter setup", description: "Sets up the server counter category and voice channels", usage: ".counter setup" },
            { name: "counter reset", description: "Deletes all counter channels and removes saved counter data", usage: ".counter reset" },
            { name: "counter update", description: "Manually updates the counter channels to reflect current stats", usage: ".counter update" },
            { name: "counter on", description: "Enables automatic updates when members join or leave", usage: ".counter on" },
            { name: "counter off", description: "Disables automatic updates when members join or leave", usage: ".counter off" },
            { name: "counter refresh", description: "Sets the interval (in minutes) for automatic counter refreshes", usage: ".counter refresh <minutes>" },
            { name: "clownboard", description: "Configure the server's clownboard message settings", usage: ".clownboard" },
            { name: "clownboard channel", description: "Configure what channel should be used to send clownboard messages", usage: ".clownboard channel <channel>" },
            { name: "clownboard color", description: "Configure what the color should be for clownboard embed messages", usage: ".clownboard color <hexcode>" },
            { name: "clownboard emoji", description: "Configure what emoji should be used to detect clownboard messages. Default is 🤡", usage: ".clownboard emoji <emoji>" },
            { name: "clownboard setup", description: "Setups the clownboard in the server, creating the channel", usage: ".clownboard setup" },
            { name: "clownboard threshold", description: "Configure what the threshold should be for clownboard messages. Default is 2 clown reactions", usage: ".clownboard threshold <number>" },
            { name: "command", description: "Configure command usage by adding restrictions for roles or permissions", usage: ".command" },
            { name: "command rolerestrictions add", description: "Add restrictions to a role to make it so only certain roles can use a command", usage: ".command rolerestrictions add (command) (roles)" },
            { name: "command rolerestrictions remove", description: "Remove a role's ability to use a certain command that was previously added", usage: ".command rolerestrictions remove (command) (roles)" },
            { name: "copyemojis", description: "Copy emojis from another server Moonlight is in", usage: ".copyemojis <server ID>" },
            { name: "createembed", description: "Create an embed using dropdown menu options", usage: ".embed" },
            { name: "custombot", description: "Configure the server's custom bot settings", usage: ".custombot" },
            { name: "custombot avatar", description: "Change the avatar of the custom bot", usage: ".custombot avatar <link>" },
            { name: "custombot name", description: "Change the name of the custom bot", usage: ".custombot name <name>" },
            { name: "custombot off", description: "Turn off custom bot usage", usage: ".custombot off" },
            { name: "custombot on", description: "Turn on custom bot usage", usage: ".custombot on" },
            { name: "custombot setup", description: "Setup the custom bot for the guild to have it functioning", usage: ".custombot setup" },
            { name: "disable", description: "Disable a command globally or in specific channels.", usage: ".disable <command> (#channel1 #channel2...)" },
            { name: "editembed", description: "Edit an embed using dropdown menu options", usage: ".editembed <message link>" },
            { name: "enable", description: "Enable the usage of a command in the server", usage: ".enable <command name>" },
            { name: "filter", description: "Configure the server's filter system for words", usage: ".filter" },
            { name: "filter add", description: "Add a word to the filter system, preventing users from saying the word", usage: ".filter add" },
            { name: "filter list", description: "View all the words that are being filtered in the server", usage: ".filter list" },
            { name: "filter remove", description: "Remove a word from the filter system, allowing users to say the word", usage: ".filter remove" },
            { name: "giveaway", description: "Create and manage giveaways within a guild to give away prizes", usage: ".giveaway <subcommand>" },
            { name: "giveaway end", description: "End a giveaway early before the time runs out", usage: ".giveaway end" },
            { name: "giveaway pause", description: "Pause a giveaway to allow users more time to react if needed", usage: ".giveaway pause" },
            { name: "giveaway reroll", description: "Reroll to get new winners of the giveaway", usage: ".giveaway reroll" },
            { name: "giveaway resume", description: "Resume a paused giveaway", usage: ".giveaway resume" },
            { name: "giveaway start", description: "Start a giveaway within a guild", usage: ".giveaway start" },
            { name: "invites", description: "View and manage top invites", usage: ".invites (subcommand)" },
            { name: "invites role add", description: "Add a role to be given when threshold uses has been reached", usage: ".invites role add <role> <uses>" },
            { name: "invites role remove", description: "Remove a role from the invite tracker", usage: ".invites role remove <role>" },
            { name: "logs", description: "Configure server logging system for different server actions and events", usage: ".logs" },
            { name: "logs off", description: "Turn off the server's logging system. No action or event messages will be sent", usage: ".logs off" },
            { name: "logs set", description: "Set the channel for logging where event and action messages will be sent", usage: ".logs set <channel>" },
            { name: "messagelinkpreview", description: "Configure server messagelinkpreview to show the content of a message whenever a message link is sent", usage: ".messagelinkpreview" },
            { name: "messagelinkpreview off", description: "Turn off the server's message link preview and have no message sent when a message link is posted", usage: ".messagelinkpreview off" },
            { name: "messagelinkpreview on", description: "Turn on the server's message link preview to have a message sent showing the content of a message link", usage: ".messagelinkpreview on" },
            { name: "messagelinkpreview restrict", description: "Add a channel to the restricted channels list so that message previews are not shown for messages from that channel", usage: ".messagelinkpreview restrict <channel_id_or_mention>" },
            { name: "messagelinkpreview unrestrict", description: "Remove a channel from the restricted channels list so that message previews are shown for messages from that channel", usage: ".messagelinkpreview unrestrict <channel_id_or_mention>" },
            { name: "messagereaction", description: "Configure the guild's message reactions", usage: ".messagereaction <subcommand> <messageLink> <emoji>" },
            { name: "messagereaction add", description: "Add the bot's reaction to a message", usage: ".messagereaction add <messageLink> <emoji>" },
            { name: "messagereaction remove", description: "Remove the bot's reaction from a message", usage: ".messagereaction remove <messageLink> <emoji>" },
            { name: "prefix", description: "Configure the bot's prefix for commands in the server", usage: ".prefix" },
            { name: "prefix reset", description: "Sets the prefix back to its default `.`", usage: ".prefix reset" },
            { name: "prefix set", description: "Set the prefix for using commands", usage: ".prefix set <prefix>" },
            { name: "reaction", description: "Configure the server's reaction triggers. Bot reactions to certain words.phrases", usage: ".reaction" },
            { name: "reaction add", description: "Add a reaction trigger to a certain word and.or phrase", usage: ".reaction add <emoji> <word or phrase>" },
            { name: "reaction list", description: "View all of the current active reaction triggers in the server", usage: ".reaction list" },
            { name: "reaction remove", description: "Remove a reaction trigger from a certain word and.or phrase", usage: ".reaction remove <emoji> <word or phrase>" },
            { name: "role", description: "Configure the server's role settings. Add.Remove role from user if no subcommand provided", usage: ".role" },
            { name: "role add", description: "Add a given role to a user", usage: ".role add <user> <role>" },
            { name: "role color", description: "Change the color of a given role", usage: ".role rcolorename <role> <color>" },
            { name: "role create", description: "Creata a role in the server", usage: ".role create <name>" },
            { name: "role info", description: "View information about a given role", usage: ".role info <role>" },
            { name: "role members", description: "View all the users who have a given role", usage: ".role members <role>" },
            { name: "role remove", description: "Remove a given role from a user", usage: ".role remove <user> <role>" },
            { name: "role rename", description: "Rename a given role", usage: ".role rename <role> <new name>" },
            { name: "safemode", description: "Configure the server's safe mode settings for search commands", usage: ".safemode" },
            { name: "safemode off", description: "Turn off the server's safemode to allow users to search explicit content", usage: ".safemode off" },
            { name: "safemode on", description: "Turn on the server's safemode to prevent users from searching explicit content", usage: ".safemode on" },
            { name: "setbanner", description: "Set the server's banner.", usage: ".setbanner <image.link>" },
            { name: "seticon", description: "Set the server's icon.", usage: ".seticon <image.link>" },
            { name: "setup", description: "Sets up Moonlight for use in guild", usage: ".setup" },
            { name: "setup jail", description: "Setup the jail channel and role and update channel permissions to allow for jailing", usage: ".setup jail" },
            { name: "starboard", description: "Configure the server's starboard message settings", usage: ".starboard" },
            { name: "starboard channel", description: "Configure what channel should be used to send starboard messages", usage: ".starboard channel <channel>" },
            { name: "starboard color", description: "Configure what the color should be for starboard embed messages", usage: ".starboard color <hexcode>" },
            { name: "starboard emoji", description: "Configure what emoji should be used to detect starboard messages. Default is ⭐", usage: ".starboard emoji <emoji>" },
            { name: "starboard setup", description: "Setups the starboard in the server, creating the channel", usage: ".starboard setup" },
            { name: "starboard threshold", description: "Configure what the threshold should be for starboard messages. Default is 2 star reactions", usage: ".starboard threshold <number>" },
            { name: "steal", description: "View recently posted emojis and clip them to add it to the server", usage: ".steal" },
            { name: "tag", description: "Configure and manage the server's tags", usage: ".tag" },
            { name: "tag add", description: "Create a tag message that can be used in the server", usage: ".tag add <tag name> <tag content>" },
            { name: "tag delete", description: "Delete a tag message from the server", usage: ".tag delete <tag name>" },
            { name: "tag list", description: "List all of the tags that are in the server", usage: ".tag list" },
            { name: "ticket", description: "Easy to use ticket system for users to create and manage tickets", usage: ".ticket" },
            { name: "voicemaster", description: "Manage voice channels", usage: ".voicemaster" },
            { name: "voicemaster allow", description: "Allow a user to join your voice channel", usage: ".voicemaster allow <user>" },
            { name: "voicemaster bitrate", description: "Set the bitrate of your voice channel", usage: ".voicemaster bitrate <bitrate>" },
            { name: "voicemaster claim", description: "Claim ownership of a voice channel", usage: ".voicemaster claim" },
            { name: "voicemaster defaultbitrate", description: "Set the default bitrate for new voice channels", usage: ".voicemaster defaultbitrate <bitrate>" },
            { name: "voicemaster defaultlimit", description: "Set the default user limit for new voice channels", usage: ".voicemaster defaultlimit <number>" },
            { name: "voicemaster defaultname", description: "Set the default name for new voice channels", usage: ".voicemaster defaultname <name>" },
            { name: "voicemaster hide", description: "Hide your voice channel", usage: ".voicemaster hide" },
            { name: "voicemaster limit", description: "Manage the user limit of your voice channel", usage: ".voicemaster limit <number>" },
            { name: "voicemaster lock", description: "Lock your voice channel", usage: ".voicemaster lock" },
            { name: "voicemaster name", description: "Set the name of your voice channel", usage: ".voicemaster name <name>" },
            { name: "voicemaster reject", description: "Reject a user from joining your voice channel", usage: ".voicemaster reject <user>" },
            { name: "voicemaster setup", description: "Set up the VoiceMaster system in the server", usage: ".voicemaster setup" },
            { name: "voicemaster unhide", description: "Unhide your voice channel", usage: ".voicemaster unhide" },
            { name: "voicemaster unlock", description: "Unlock your voice channel", usage: ".voicemaster unlock" },
            { name: "welcome", description: "Configure the server's welcome system for users who join.leave the server", usage: ".welcome" },
            { name: "welcome off", description: "Turn off the server's welcome system. No join or leave messages will be sent", usage: ".welcome off" },
            { name: "welcome set", description: "Set the channel for join.leave messages to be sent", usage: ".welcome set <channel>" },
        ],
    },
]
